Fix/build
Innovattic/App-Badge pull request #1
Opened 2021-08-30 18:52 UTC by InnoLuke

Fix the project for gradle 7. The actual fix is pretty small (removing a deprecated API and replacing it with the new one), but I also made a lot of unrelated changes to get the project to build. I also removed the sample from this repo, to avoid ending up in a gradle deadlock when trying to build the plugin.

2021-09-06 16:50 UTC, nbruning requested changes

2021-09-06 16:50 UTC, nbruning commented on .gitignore
> +/plugin/build/
Just exclude `build` in general? patterns are recursive by default, if i remember correctly

2021-09-06 16:50 UTC, nbruning commented on README.md
> +You can find the sample in a separate repo.
Let's use a link :)

2021-09-06 16:50 UTC, nbruning commented on README.md
> +Every time you change the plugin, you need to re-run `./gradlew publishToMavenLocal` in order to update the
So this isn't great either. Any chance of keeping the project+demo together, in a way that it does work?

It would also have a great benefit of being testable - ie. you'd be forced to update the lib+demo project simultaneously for any breaking change - if we have a CI setup.

2021-09-06 16:50 UTC, nbruning commented on plugin/build.gradle.kts
> +    `maven-publish`
Did you actually try to upload anything to anywhere?

2021-09-14 07:49 UTC, InnoLuke commented on plugin/build.gradle.kts
> +    `maven-publish`
Only local publish for now

2021-09-14 08:33 UTC, InnoLuke commented on README.md
> +Every time you change the plugin, you need to re-run `./gradlew publishToMavenLocal` in order to update the
As discussed, we'll leave it like this for now

2021-09-14 13:45 UTC, InnoLuke commented on .gitignore
> +/plugin/build/
Nice, you remembered correctly

2021-09-14 13:45 UTC, InnoLuke commented on README.md
> +You can find the sample in a separate repo.
Done

2021-09-14 15:01 UTC, merged

2021-09-17 13:56 UTC, nbruning commented on README.md
> +This will publish the plugin to the local `/.m2` folder on your machine.
`~/.m2`

2021-09-17 13:56 UTC, nbruning commented on README.md
> +## Maintained by
This fork is now maintained by Innovattic